sonar.projectKey=Youngyz1_registration-app-EKS
sonar.organization=youngyz1
sonar.sources=backend,frontend/src
sonar.python.version=3.9
sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**,**/build/**
