apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_NAME: {{ .Values.secrets.dbName | quote }}
  DB_HOST: {{ .Values.secrets.dbHost | quote }}
  DB_PORT: {{ .Values.secrets.dbPort | quote }}
  DATABASE_URL: "postgresql://{{ .Values.secrets.dbUser }}:{{ .Values.secrets.dbPassword }}@{{ .Values.secrets.dbHost }}:{{ .Values.secrets.dbPort }}/{{ .Values.secrets.dbName }}"
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  POSTGRES_USER: {{ .Values.secrets.dbUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.dbName | quote }}
